---

# is curl installed
- name: Check if curl is installed on macOS or Ubuntu
  stat:
    path: "{{ curl_path }}"
  register: curl_installed
  ignore_errors: yes
  tags: awscli

- debug:
    var: curl_installed.stdout

# if curl is not installed, install it on macOS
- name: Install curl on macOS
  command: brew install curl
  when: curl_installed.stat.exists == false and ansible_os_family == 'Darwin'
  tags: awscli

# if curl is not installed, install it on Ubuntu
- name: Install curl on Ubuntu
  apt:
    name: curl
    state: present
  when: curl_installed.stat.exists == false and ansible_os_family == 'Debian'
  become: yes
  tags: awscli
