---

- name: Download AWS CLI package file on macOS
  ansible.builtin.get_url:
    url: '{{ awscli_url }}/{{ awscli_pkg }}'
    dest: '{{ download_dir }}/{{ awscli_pkg }}'
    mode: '0660'
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'
  tags: awscli

- name: Download AWS CLI zip file on Ubuntu
  ansible.builtin.get_url:
    url: '{{ awscli_url }}/{{ awscli_zip }}'
    dest: '{{ download_dir }}/awscliv2.zip'
    mode: '0660'
  ignore_errors: yes
  become: yes
  when: ansible_os_family == 'Debian'
  tags: awscli
