---

- name: Unarchive the AWS CLI zip file on Ubuntu only
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/awscliv2.zip"
    dest: "{{ download_dir }}"
    remote_src: false
  failed_when: false

  become: true
  become_method: ansible.builtin.sudo
