---

- name: Install AWS CLI on macOS
  command: sudo installer -pkg "{{ download_dir }}/{{ awscli_pkg }}" -target /
  when: ansible_os_family == 'Darwin'
  become: yes
  tags: awscli

- name: Install AWS CLI on Ubuntu
  command: sudo ./aws/install
  chdir: "{{ download_dir }}"
  when: ansible_os_family == 'Debian'
  become: yes
  tags: awscli
