---

- name: Install AWS CLI on macOS
  ansible.builtin.command: installer -pkg "{{ download_dir }}"/"{{ awscli_pkg }}" -target /
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_os_family == 'Darwin'
  changed_when: "'aws' not in ansible_facts.packages"

- name: Install AWS CLI on Ubuntu
  ansible.builtin.command: ./aws/install
  args:
    chdir: "{{ download_dir }}"
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_os_family == 'Debian'
  changed_when: "'aws' not in ansible_facts.packages"
