---
# tasks file for roles/awscli

- name: Check if the software is already installed
  ansible.builtin.include_tasks: check.yml
  tags: awscli

- name: Download, extract, install & verify the software
  when: not awscli_installed.stat.exists
  tags: awscli
  block:
    - name: Download the software
      ansible.builtin.include_tasks: download.yml
    - name: If Linux based, unzip archive first
      ansible.builtin.include_tasks: extract.yml
      when: ansible_os_family == 'Debian'
    - name: Install the software
      ansible.builtin.include_tasks: install.yml
    - name: Verify the install
      ansible.builtin.include_tasks: verify.yml
