---
# tasks file for roles/awscli

- include_tasks: check.yml

- block:
    - include_tasks: curl.yml
    - include_tasks: download.yml
    - include_tasks: extract.yml
      when: ansible_os_family == 'Debian'
    - include_tasks: install.yml
    - include_tasks: verify.yml
  when: awscli_installed.stat.exists == false