---
# tasks file for roles/awscli

- name: Verify AWS CLI on macOS - install path
  command: which aws
  register: awscli_path
  when: ansible_os_family == 'Darwin'
  tags: awscli

- debug:
    var: awscli_path.stdout
  when: ansible_os_family == 'Darwin'

- name: Verify AWS CLI on Ubuntu - install path
  command: which aws
  register: awscli_path
  when: ansible_os_family == 'Debian'
  tags: awscli

- debug:
    var: awscli_path.stdout
  when: ansible_os_family == 'Debian'

- name: Verify AWS CLI on macOS - version
  command: aws --version
  register: awscli_version
  Debian
  tags: awscli

- debug:
    var: awscli_version.stdout
  when: ansible_os_family == 'Darwin'

- name: Verify AWS CLI on Ubuntu - version
  command: aws --version
  register: awscli_version
  when: ansible_os_family == 'Debian'
  tags: awscli

- debug:
    var: awscli_version.stdout
  when: ansible_os_family == 'Debian'