---
# tasks file for roles/amethyst

# is amethyst installed is installed PRIOR to installing and if yes skip installation
- name: Check if amethyst is already installed?
  ansible.builtin.stat:
    path: "{{ amethyst_path }}"
  register: amethyst_installed
  failed_when: false

- name: Debug amethyst_installed
  ansible.builtin.debug:
    var: amethyst_installed.stat.exists
