---
# tasks file for roles/amethyst

- name: Install amethyst on macOS using Homebrew
  community.general.homebrew:
    name: amethyst
    state: present
    update_homebrew: true
  when: ansible_os_family == 'Darwin' and ansible_facts.packages['amethyst'] is not defined
  become: false
