---
# tasks file for roles/amethyst

- name: Get install path
  ansible.builtin.command:
    cmd: "brew list amethyst"
  register: amethyst_path
  changed_when: false
  failed_when: false

- name: Display install path
  ansible.builtin.debug:
    var: amethyst_path.stdout
  changed_when: false
  failed_when: false

- name: Get version
  ansible.builtin.command:
    cmd: "brew info amethyst"
  register: amethyst_version
  changed_when: false
  failed_when: false

- name: Display version
  ansible.builtin.debug:
    var: amethyst_version.stdout
  changed_when: false
  failed_when: false
