---
# tasks file for roles/autoconf

- name: Install autoconf on macOS using Homebrew
  community.general.homebrew:
    name: autoconf
    state: present
    update_homebrew: true
  when: ansible_os_family == 'Darwin'
  become: false

- name: Install autoconf on Ubuntu using apt
  ansible.builtin.apt:
    name: autoconf
    state: present
  when: ansible_os_family == 'Debian'
  become: true
  become_method: ansible.builtin.sudo
