---
# tasks file for roles/autoconf

- name: Install autoconf on macOS
  community.general.homebrew:
    name: autoconf
    state: present
    update_homebrew: true
  when: ansible_os_family == 'Darwin'
  become: no
  tags: autoconf

- name: Install autoconf on Ubuntu
  apt:
    name: autoconf
    state: present
  when: ansible_os_family == 'Debian'
  become: yes
  tags: autoconf