---
# tasks file for roles/autoconf

- name: Get install path
  ansible.builtin.command:
    cmd: "which autoconf"
  register: autoconf_path
  changed_when: false

- name: Display install path
  ansible.builtin.debug:
    var: autoconf_path.stdout
  changed_when: false

- name: Get version
  ansible.builtin.command:
    cmd: "autoconf --version"
  register: autoconf_version
  changed_when: false

- name: Display version
  ansible.builtin.debug:
    var: autoconf_version.stdout
  changed_when: false
